# Generated by Django 5.1.7 on 2025-03-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
